
 const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
 const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
 const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

 const CATEGORY_LIST_REQUEST_SRC = 'CATEGORY_LIST_REQUEST_SRC';
 const CATEGORY_LIST_SUCCESS_SRC = 'CATEGORY_LIST_SUCCESS_SRC';
 const CATEGORY_LIST_FAIL_SRC = 'CATEGORY_LIST_FAIL_SRC';
 
 const CATEGORY_LIST_REQUEST_CARR = 'CATEGORY_LIST_REQUEST_CARR';
 const CATEGORY_LIST_SUCCESS_CARR = 'CATEGORY_LIST_SUCCESS_CARR';
 const CATEGORY_LIST_FAIL_CARR = 'CATEGORY_LIST_FAIL_CARR';
 
 const CATEGORY_SAVE_REQUEST = 'CATEGORY_SAVE_REQUEST';
 const CATEGORY_SAVE_SUCCESS = 'CATEGORY_SAVE_SUCCESS';
 const CATEGORY_SAVE_COMPLETE = 'CATEGORY_SAVE_COMPLETE';
 const CATEGORY_SAVE_FAIL = 'CATEGORY_SAVE_FAIL';

 const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
 const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
 const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';
 
export  {
//module.exports = {
 CATEGORY_LIST_REQUEST ,
 CATEGORY_LIST_SUCCESS ,
 CATEGORY_LIST_FAIL ,

 CATEGORY_LIST_REQUEST_SRC ,
 CATEGORY_LIST_SUCCESS_SRC ,
 CATEGORY_LIST_FAIL_SRC ,

 CATEGORY_LIST_REQUEST_CARR ,
 CATEGORY_LIST_SUCCESS_CARR ,
 CATEGORY_LIST_FAIL_CARR ,


 CATEGORY_SAVE_REQUEST ,
 CATEGORY_SAVE_SUCCESS ,
 CATEGORY_SAVE_COMPLETE ,
 CATEGORY_SAVE_FAIL ,

 CATEGORY_DELETE_REQUEST ,
 CATEGORY_DELETE_SUCCESS ,
 CATEGORY_DELETE_FAIL ,
}