
 const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
 const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
 const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

 const CATEGORY_SAVE_REQUEST = 'CATEGORY_SAVE_REQUEST';
 const CATEGORY_SAVE_SUCCESS = 'CATEGORY_SAVE_SUCCESS';
 const CATEGORY_SAVE_COMPLETE = 'CATEGORY_SAVE_COMPLETE';
 const CATEGORY_SAVE_FAIL = 'CATEGORY_SAVE_FAIL';

 const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
 const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
 const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';
 
module.exports = {
 CATEGORY_LIST_REQUEST ,
 CATEGORY_LIST_SUCCESS ,
 CATEGORY_LIST_FAIL ,

 CATEGORY_SAVE_REQUEST ,
 CATEGORY_SAVE_SUCCESS ,
 CATEGORY_SAVE_COMPLETE ,
 CATEGORY_SAVE_FAIL ,

 CATEGORY_DELETE_REQUEST ,
 CATEGORY_DELETE_SUCCESS ,
 CATEGORY_DELETE_FAIL ,
}