
const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST';
const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';

const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
const UPLOAD_IMAGE_COMPLETE = 'UPLOAD_IMAGE_COMPLETE';
const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';

module.exports = {
    PRODUCT_LIST_REQUEST,
    PRODUCT_LIST_SUCCESS,
    PRODUCT_LIST_FAIL,

    PRODUCT_SAVE_REQUEST,
    PRODUCT_SAVE_SUCCESS,
    PRODUCT_SAVE_FAIL,

    PRODUCT_DELETE_REQUEST,
    PRODUCT_DELETE_SUCCESS,
    PRODUCT_DELETE_FAIL,

    UPLOAD_IMAGE_REQUEST,
    UPLOAD_IMAGE_SUCCESS,
    UPLOAD_IMAGE_COMPLETE,
    UPLOAD_IMAGE_FAIL,
}